$schema: "http://json-schema.org/draft-04/schema#"

id: "metaschema"
title: "GDC JSON schema extension"

allOf:
  - $ref: "http://json-schema.org/draft-04/schema#"

#GDC extensions
required:
  - category #potentially used in submission system, if not may not be needed
  - program
  - project
  - uniqueKeys #for validator to check uniqueness
  - links #to specify to the validator what properties are links and their targets
  - validators #specify to the validator additional functions to run on the values
  - systemProperties #non-user facing values required by backend
  #Require core JSON schema fields here if desired, requiring id
  - id

field:
  type: string
  pattern: "^[_a-zA-Z0-9]*$"

definitions:

  link:
    type: object
    additionalProperties: false
    required:
      - name
      - target_type
      - backref
      - label
      - multiplicity
      - required
    properties:
      name:
        $ref: "#/field"
      target_type:
        $ref: "#/field"
      backref:
        $ref: "#/field"
      label:
        $ref: "#/field"
      multiplicity:
        type: string
        enum:
          - one_to_one
          - one_to_many
          - many_to_one
          - many_to_many
      required:
        type: boolean

  link_subgroup:
    required:
      - exclusive
      - required
      - subgroup
    properties:
      exclusive:
        type: boolean
      required:
        type: boolean
      subgroup:
        type: array
        items:
          oneOf:
            - $ref: "#/definitions/link"
            - $ref: "#/definitions/link_subgroup"

  validator_def:
    title: "Define a validator to be used on a property"
    type: object
    required:
      - property #the property to be applied to
      - function #the function name, predefined somewhere, to use

    properties:
      link_to_type:
        type: string

      multiplicity:
        type: string
        enum:
          - one_to_one
          - one_to_many
          - many_to_one
          - many_to_many

properties:
  category:
    $ref: "#/field"
    enum:
      - administrative
      - analysis
      - biospecimen
      - clinical
      - data
      - data_bundle
      - data_file
      - index_file
      - metadata_file
      - notation
      - qc_bundle
      - TBD

  unique_keys:
    type: array
    items:
      type: array
      items:
        type: string

  submittable:
    type: boolean

  validators:
    type:
      - array
      - "null"
    items:
      $ref: "#/definitions/validator_def"

  system_properties:
    type: array
  properties:
    type: object
    patternProperties:
      "^[_a-zA-Z0-9]*$":
        type: object
    additionalProperties: false
  links:
    title: "Define a link to other GDC entities"
    type: array
    items:
      oneOf:
        - $ref: "#/definitions/link"
        - $ref: "#/definitions/link_subgroup"
