global:
  hostname: localhost

fence: 
  FENCE_CONFIG:
    MOCK_GOOGLE_AUTH: true
    OPENID_CONNECT:
      google:
        mock_default_user: 'test@example.com'
  USER_YAML: |
    cloud_providers: {}
    authz:
      # policies automatically given to anyone, even if they are not authenticated
      anonymous_policies: []

      # policies automatically given to authenticated users (in addition to their other policies)
      all_users_policies: []

      groups:
      # ARDaC administrators
      # Full system access, including data upload.
      - name: admins
        policies:
        - workspace
        - data_upload
        - services.sheepdog-admin
        - indexd_admin
        - open_data_reader
        - all_programs_reader
        - audit_reader
        users:
        - test@example.com

      resources:
      - name: audit
        subresources:
        - name: presigned_url
        - name: login
      - name: workspace
      - name: data_file
      - name: services
        subresources:
        - name: sheepdog
          subresources:
          - name: submission
            subresources:
            - name: program
            - name: project
        - name: indexd
          subresources:
            - name: admin
        - name: audit
          subresources:
            - name: presigned_url
            - name: login
      - name: open
      - name: programs

      policies:
      - id: audit_reader
        role_ids:
        - audit_reader
        resource_paths:
        - /services/audit
      - id: presigned_url_audit_reader
        role_ids:
        - audit_reader
        resource_paths:
        - /services/audit/presigned_url
      - id: login_audit_reader
        role_ids:
        - audit_reader
        resource_paths:
        - /services/audit/login
      - id: workspace
        description: be able to use workspace
        resource_paths:
        - /workspace
        role_ids:
        - workspace_user
      - id: data_upload
        description: upload raw data files to S3
        role_ids:
        - file_uploader
        resource_paths:
        - /data_file
      - id: services.sheepdog-admin
        description: CRUD access to programs and projects
        role_ids:
          - sheepdog_admin
        resource_paths:
          - /services/sheepdog/submission/program
          - /services/sheepdog/submission/project
      - id: indexd_admin
        description: full access to indexd API
        role_ids:
          - indexd_admin
        resource_paths:
          - /programs
      - id: open_data_reader
        role_ids:
          - reader
          - storage_reader
        resource_paths:
        - /open
      - id: all_programs_reader
        role_ids:
        - reader
        - storage_reader
        resource_paths:
        - /programs

      roles:
      - id: audit_reader
        permissions:
        - id: audit_reader_action
          action:
            service: audit
            method: read
      - id: file_uploader
        permissions:
        - id: file_upload
          action:
            service: fence
            method: file_upload
      - id: workspace_user
        permissions:
        - id: workspace_access
          action:
            service: jupyterhub
            method: access
      - id: sheepdog_admin
        description: CRUD access to programs and projects
        permissions:
        - id: sheepdog_admin_action
          action:
            service: sheepdog
            method: '*'
      - id: indexd_admin
        description: full access to indexd API
        permissions:
        - id: indexd_admin
          action:
            service: indexd
            method: '*'
      - id: admin
        permissions:
          - id: admin
            action:
              service: '*'
              method: '*'
      - id: creator
        permissions:
          - id: creator
            action:
              service: '*'
              method: create
      - id: reader
        permissions:
          - id: reader
            action:
              service: '*'
              method: read
      - id: updater
        permissions:
          - id: updater
            action:
              service: '*'
              method: update
      - id: deleter
        permissions:
          - id: deleter
            action:
              service: '*'
              method: delete
      - id: storage_writer
        permissions:
          - id: storage_creator
            action:
              service: '*'
              method: write-storage
      - id: storage_reader
        permissions:
          - id: storage_reader
            action:
              service: '*'
              method: read-storage

    clients:
      wts:
        policies:
        - all_programs_reader
        - open_data_reader

    users:
      test@example.com:
        admin: true
        policies:
        - data_upload
        - workspace
        - services.sheepdog-admin
        - indexd_admin
        - open_data_reader
        - all_programs_reader
        - audit_reader
