global:
  hostname: localhost

fence: 
  FENCE_CONFIG:
    MOCK_GOOGLE_AUTH: true
    OPENID_CONNECT:
      google:
        mock_default_user: 'test@example.com'

postgresql:
  primary:
    persistence:
      enabled: true
