global:
  hostname: localhost
  dictionaryUrl: https://dictionary.ardac.org/1.0.0/schema.json

fence:
  FENCE_CONFIG:
    MOCK_GOOGLE_AUTH: true
    OPENID_CONNECT:
      google:
        mock_default_user: 'test@example.com'
  USER_YAML: |
    cloud_providers: {}
    authz:
      # policies automatically given to anyone, even if they are not authenticated
      anonymous_policies: ['open_data_reader']

      # policies automatically given to authenticated users (in addition to their other policies)
      all_users_policies: ['open_data_reader']

      groups:
      # ARDaC administrators
      # Full system access, including data upload.
      - name: admins
        policies:
        - workspace
        - data_upload
        - services.sheepdog-admin
        - indexd_admin
        - open_data_reader
        - all_programs_reader
        - ARDaC_admin
        - audit_reader
        users:
        - test@example.com

      resources:
      - name: audit
        subresources:
        - name: presigned_url
        - name: login
      - name: workspace
      - name: data_file
      - name: services
        subresources:
        - name: sheepdog
          subresources:
          - name: submission
            subresources:
            - name: program
            - name: project
        - name: indexd
          subresources:
            - name: admin
        - name: audit
          subresources:
            - name: presigned_url
            - name: login
      - name: open
      - name: programs
        subresources:
        - name: ARDaC
          subresources:
          - name: projects
            subresources:
            - name: AlcHepNet

      policies:
      - id: audit_reader
        role_ids:
        - audit_reader
        resource_paths:
        - /services/audit
      - id: presigned_url_audit_reader
        role_ids:
        - audit_reader
        resource_paths:
        - /services/audit/presigned_url
      - id: login_audit_reader
        role_ids:
        - audit_reader
        resource_paths:
        - /services/audit/login
      - id: workspace
        description: be able to use workspace
        resource_paths:
        - /workspace
        role_ids:
        - workspace_user
      - id: data_upload
        description: upload raw data files to S3
        role_ids:
        - file_uploader
        resource_paths:
        - /data_file
      - id: services.sheepdog-admin
        description: CRUD access to programs and projects
        role_ids:
          - sheepdog_admin
        resource_paths:
          - /services/sheepdog/submission/program
          - /services/sheepdog/submission/project
      - id: indexd_admin
        description: full access to indexd API
        role_ids:
          - indexd_admin
        resource_paths:
          - /programs
      - id: open_data_reader
        role_ids:
          - reader
          - storage_reader
        resource_paths:
        - /open
      - id: all_programs_reader
        role_ids:
        - reader
        - storage_reader
        resource_paths:
        - /programs
      - id: ARDaC_admin
        role_ids:
        - reader
        - creator
        - updater
        - deleter
        - storage_reader
        - storage_writer
        resource_paths:
        - /programs/ARDaC
        - /programs/ARDaC/projects/AlcHepNet

      roles:
      - id: audit_reader
        permissions:
        - id: audit_reader_action
          action:
            service: audit
            method: read
      - id: file_uploader
        permissions:
        - id: file_upload
          action:
            service: fence
            method: file_upload
      - id: workspace_user
        permissions:
        - id: workspace_access
          action:
            service: jupyterhub
            method: access
      - id: sheepdog_admin
        description: CRUD access to programs and projects
        permissions:
        - id: sheepdog_admin_action
          action:
            service: sheepdog
            method: '*'
      - id: indexd_admin
        description: full access to indexd API
        permissions:
        - id: indexd_admin
          action:
            service: indexd
            method: '*'
      - id: admin
        permissions:
          - id: admin
            action:
              service: '*'
              method: '*'
      - id: creator
        permissions:
          - id: creator
            action:
              service: '*'
              method: create
      - id: reader
        permissions:
          - id: reader
            action:
              service: '*'
              method: read
      - id: updater
        permissions:
          - id: updater
            action:
              service: '*'
              method: update
      - id: deleter
        permissions:
          - id: deleter
            action:
              service: '*'
              method: delete
      - id: storage_writer
        permissions:
          - id: storage_creator
            action:
              service: '*'
              method: write-storage
      - id: storage_reader
        permissions:
          - id: storage_reader
            action:
              service: '*'
              method: read-storage

    clients:
      wts:
        policies:
        - all_programs_reader
        - open_data_reader

    users:
      test@example.com:
        admin: true
        policies:
        - data_upload
        - workspace
        - services.sheepdog-admin
        - indexd_admin
        - open_data_reader
        - all_programs_reader
        - audit_reader

# The following is not being picked up, even though the template should resolve it https://github.com/uc-cdis/gen3-helm/blob/feat/es7/helm/portal/templates/deployment.yaml
#portal:
#  image:
#    repository: windmill
#    pullPolicy: Never
#    tag: latest

## from https://github.com/Su-informatics-lab/cdis-manifest/blob/feat/ardac-branches/dev.ardac.org/etlMapping.yaml
etl:
  enabled: true
  etlMapping:
    mappings:
      - name: ardac_case
        doc_type: case
        type: aggregator
        root: case
        props:
          - name: pat_id
            src: submitter_id
          - name: project_id
          - name: group
            src: cohort
          # - name: cohort
          - name: study_site
          - name: actarm
          - name: aki_status
          - name: days_180_aki
          - name: days_180_survival
          - name: days_90_aki
          - name: days_90_survival
          - name: days_to_aki
        parent_props:
          - path: studies[study_name, study_id:submitter_id]
        flatten_props:
          - path: demographics
            props:
              - name: gender
                value_mappings:
                  - female: Female
                  - male: Male
              - name: race
                value_mappings:
                  - white: White
                  - black or african american: Black or African American
                  - asian: Asian
                  - Unknown: Unknown
                  - american indian or alaska native: American Indian or Alaska Native
                  - native hawaiian or other pacific islander: Native Hawaiian or other Pacific Islander
              - name: ethnicity
                value_mappings:
                  - not hispanic or latino: Not Hispanic or Latino
                  - hispanic or latino: Hispanic or Latino
                  - Unknown: Unknown
              - name: year_of_birth
              - name: age_at_index
          - path: audits
            props:
              - name: drinking_frequency
                src: adt0101
              - name: drinks_per_day
                src: adt0102
              - name: frequency_of_heavy_drinking
                src: adt0103
        aggregated_props:
          - name: visit_day
            path: follow_ups
            src: visit_day
            fn: max
          - name: visit_day_set
            path: follow_ups
            src: visit_day
            fn: set
          - name: laboratory_test
            path: follow_ups.molecular_tests
            src: laboratory_test
            fn: set

      - name: ardac_follow_up
        parent_props:
          - path: cases[pat_id:submitter_id, case_arm:actarm, case_group:cohort, study_site, aki_status, days_180_aki, days_180_survival, days_90_aki, days_90_survival, days_to_aki].studies[study_name, study_id:submitter_id]
          - path: demographics[gender, race, ethnicity, year_of_birth, age_at_index]
            value_mappings:
              - white: White
              - black or african american: Black or African American
              - asian: Asian
              - Unknown: Unknown
              - american indian or alaska native: American Indian or Alaska Native
              - native hawaiian or other pacific islander: Native Hawaiian or other Pacific Islander
        doc_type: follow_up
        type: aggregator
        root: follow_up
        props:
          - name: project_id
          - name: follow_up_id
            src: submitter_id
          - name: visit_day
          - name: bmi
          - name: child_pugh_score
          - name: lille_score
          - name: maddreys_score
          - name: meld_score
        aggregated_props:
          - name: laboratory_test
            path: molecular_tests
            src: laboratory_test
            fn: set
          - name: specimen_type
            path: aliquots
            src: specimen_type
            fn: set
        # joining_props:
        #   - index: case      # the index to join on
        #     join_on: pat_id # the identifier to join on (it should be in both indices)
        #     props:
        #     - name: gender
        #       src: gender
        #       fn: set

      - name: ardac_biospecimen
        doc_type: aliquot
        type: aggregator
        root: aliquot
        props:
          - name: project_id
          - name: aliquot_id
            src: submitter_id
          - name: specimen_type
        parent_props:
          - path: follow_ups[follow_up_id:submitter_id, visit_day].cases[pat_id:submitter_id, case_arm:actarm].studies[study_name, study_id:submitter_id]
          - path: follow_ups.cases[pat_id:submitter_id, case_arm:actarm, case_group:cohort, study_site, aki_status, days_180_aki, days_180_survival, days_90_aki, days_90_survival, days_to_aki]
          - path: labs[lab_id:submitter_id, lab_name:name_of_institute]
          - path: follow_ups.demographics[gender, race, ethnicity, year_of_birth, age_at_index]

      - name: ardac_lab_result
        doc_type: molecular_test
        type: aggregator
        root: molecular_test
        parent_props:
          - path: follow_ups[follow_up_id:submitter_id, visit_day].cases[pat_id:submitter_id, case_arm:actarm].studies[study_name, study_id:submitter_id]
          - path: follow_ups.cases[pat_id:submitter_id, case_arm:actarm, case_group:cohort, study_site, aki_status, days_180_aki, days_180_survival, days_90_aki, days_90_survival, days_to_aki]
          - path: follow_ups.demographics[gender, race, ethnicity, year_of_birth, age_at_index]
          - path: aliquots.labs[lab_id:submitter_id, lab_name:name_of_institute]
        props:
          - name: project_id
          - name: molecular_test_id
            src: submitter_id
          - name: laboratory_test
          - name: test_result
          - name: test_value

        # - name: ardac_lab
        #   doc_type: lab
        #   type: aggregator
        #   root: lab
        #   props:
        #     - name: project_id
        #     - name: submitter_id
        #     - name: name_of_institute
        # aggregated_props:
        #   - name: specimen_type
        #     path: aliquots
        #     src: specimen_type
        #     fn: set
        #   - name: laboratory_test
        #     path: aliquots.molecular_tests
        #     src: laboratory_test
        #     fn: set

postgresql:
  primary:
    persistence:
      enabled: true
